# Generated by Django 3.0 on 2021-11-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnAI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('whatsup', models.BigIntegerField()),
                ('occupation', models.CharField(max_length=50)),
                ('Looking', models.CharField(max_length=50)),
                ('department1', models.CharField(max_length=15)),
                ('department2', models.CharField(max_length=50)),
                ('department3', models.CharField(max_length=50)),
                ('department4', models.CharField(max_length=50)),
                ('department5', models.CharField(max_length=50)),
                ('department6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LearnAI_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('whatsup', models.BigIntegerField()),
                ('occupation', models.CharField(max_length=50)),
                ('Looking', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=15)),
                ('type1', models.CharField(max_length=50)),
                ('projects', models.CharField(max_length=50)),
                ('student', models.CharField(max_length=50)),
            ],
        ),
    ]
