# Generated by Django 3.0 on 2021-11-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnAI_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('whatsup', models.BigIntegerField()),
                ('occupation', models.CharField(max_length=50)),
                ('Looking', models.CharField(max_length=50)),
                ('intern1', models.CharField(max_length=15)),
                ('internship', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
