# Generated by Django 3.0 on 2021-11-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0002_learnai_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnAI_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('whatsup', models.BigIntegerField()),
                ('occupation', models.CharField(max_length=50)),
                ('Looking', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=15)),
                ('job1', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LearnAI_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('whatsup', models.BigIntegerField()),
                ('occupation', models.CharField(max_length=50)),
                ('Looking', models.CharField(max_length=50)),
                ('visa', models.CharField(max_length=15)),
                ('visa1', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
