# Generated by Django 3.0 on 2021-11-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0003_learnai_4_learnai_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnAI_6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('whatsup', models.BigIntegerField()),
                ('occupation', models.CharField(max_length=50)),
                ('Looking', models.CharField(max_length=50)),
                ('job_assi', models.CharField(max_length=15)),
                ('job_assi1', models.CharField(max_length=50)),
            ],
        ),
    ]
